name=ARAM_Toggle_Actuator
version=1.0.5
author=A.R.A.M. - American Robotics Assisted Manufacturing
maintainer=A.R.A.M. - American Robotics Assisted Manufacturing <support@aram-usa.com>
sentence=Driver for A.R.A.M. Toggle Actuators
paragraph=This is a driver maintianed for all models of A.R.A.M. toggle actuators. Currently this applies to the ARAM-MOTCA_0_10_0SP. This library is made spefically to avoid high overhead, especially with ESP32 units. Please view the manual for information on usage.
category=Device Control
url=https://github.com/ARAM-USA-Support/ARAM_Toggle_Actuator
architectures=*s
